export const SET_LOCAL_WORDS = 'SET_LOCAL_WORDS';
export const SET_CURRENT_WORDS = 'SET_CURRENT_WORDS';
export const ADD_NEW_LOCAL_WORDS = 'ADD_NEW_LOCAL_WORDS';
export const REMOVE_DELETED_LOCAL_WORDS = 'REMOVE_DELETED_LOCAL_WORDS';
export const CLEAR_WORDS_TO_DELETE = 'CLEAR_WORDS_TO_DELETE';
