export const SET_LOCAL_CONTENT = 'SET_LOCAL_CONTENT';
export const SET_CURRENT_CONTENT = 'SET_CURRENT_CONTENT';
export const SAVE_TEXT_CONTENT = 'SAVE_TEXT_CONTENT';
export const SAVE_TEXT_CONTENT_SUCCESS = 'SAVE_TEXT_CONTENT_SUCCESS';
export const SAVE_TEXT_CONTENT_FAILURE = 'SAVE_TEXT_CONTENT_FAILURE';
