export const SET_TEXT_ITEMS = 'SET_TEXT_ITEMS';
export const SET_CURRENT_TEXT_ID = 'SET_CURRENT_TEXT_ID';
export const FETCH_TEXT_ITEMS = 'FETCH_TEXT_ITEMS';
export const FETCH_TEXT_ITEMS_SUCCESS = 'FETCH_TEXT_ITEMS_SUCCESS';
export const FETCH_TEXT_ITEMS_FAILURE = 'FETCH_TEXT_ITEMS_FAILURE';
