export const SET_LOCAL_CHARS = 'SET_LOCAL_CHARS';
export const SET_CURRENT_CHARS = 'SET_CURRENT_CHARS';
export const ADD_NEW_LOCAL_CHARS = 'ADD_NEW_LOCAL_CHARS';
export const REMOVE_DELETED_LOCAL_CHARS = 'REMOVE_DELETED_LOCAL_CHARS';
export const CLEAR_CHARS_TO_DELETE = 'CLEAR_CHARS_TO_DELETE';
export const SET_CHAR_VISIBILITY_FILTER = 'SET_CHAR_VISIBILITY_FILTER';
